### ISSUE TITLE
Multi-line literal strings

### ISSUE THREAD

**Issue by programmergrammar** [Jonarod/markty-TOML#3]
I would love to see multi-line literal strings added. This can be really helpful for readability of TOML data:

```
lines  = '''
The first newline is
trimmed in raw strings.
   All other whitespace
   is preserved.
'''
```

**Comment by Jonarod** [comment]
Is that not working for you :

```
lines = "
The first newline is
trimmed in raw strings.
   All other whitespace
   is preserved.
"
```
??

[https://jsfiddle.net/8eb91yfj/1/](https://jsfiddle.net/8eb91yfj/1/)

**Comment by Jonarod** [comment]
Since the output is JSON, I don't really see how you would like to keep "raw string". However, in the fiddle I posted above, you can see the formatting is respected: new lines prints a `\n` and white spaces are preserved.
Did I miss something ?

**Comment by programmergrammar** [comment]
This all works well until you need to have a " in your string.  Then you have to escape it.  Three single quotes (or double quotes) in a row is much more unlikely.

I was going to use this to hold some HTML snippets as the string values and was hoping to not have to worry so much about escaping all the double quotes and still be able to have multi-lines.

Here is a link to the TOML example:
https://github.com/toml-lang/toml/blob/master/examples/example-v0.4.0.toml#L94

**Comment by programmergrammar** [comment]
Something like this would be great too:
```
lines = "
line one
line two
"line" three
line four
"
```
```
{
    "lines": "\nline one\nline two\n\"line\" three\nline four\n"
}
```

**Comment by programmergrammar** [comment]
Here is what is did to make it work:
```javascript
function preprocessTOML(tomlString) {
  var result = '';
  var multilineSecions = tomlString.split(" = '''\n")
  for (iSection = 0; iSection < multilineSecions.length; iSection++) {
    var multilineSecionTopBottom = multilineSecions[iSection].split("\n'''\n");
    for (iTopBottom = 0; iTopBottom < multilineSecionTopBottom.length; iTopBottom++) {
      if (iTopBottom == 0 && multilineSecionTopBottom.length > 1) {
        result = result + " = \"\n" + multilineSecionTopBottom[iTopBottom].replace(/"/g, "{{{-dq-}}}") + "\n\"\n\n";
      } else {
        result = result + multilineSecionTopBottom[iTopBottom];
      }
    }
  }
  return result;
}

function postprocessTOML(tomlString) {
  return tomlString.replace(/{{{-dq-}}}/g, "\\\"");
}
```

https://jsfiddle.net/bixfliz/y37s1uko/

I'm just transforming the TOML into something that your parser can work with and then converting the double quotes back after it's parsed.

**Comment by Jonarod** [comment]
Sorry for late reply.
Would character escaping (with `\`) be a fit ?

Like:
```
lines = "
line one
line two
\"line\" three
line four
"
```
resulting in:

```json
{
  "lines": "\nline one\nline two\n\"line\" three\nline four\n"
}
```

**Comment by Jonarod** [comment]
Hmmm let me think about it a little more, I think I came to a solution that fits into official v0.4 specs

**Comment by programmergrammar** [comment]
I ended up having up update my preprocess/postprocess code like this since I found that the [ and ] characters also cause problems in the multi-line sections:

```js
function preprocessTOML(tomlString) {
  var result = '';
  var multilineSecions = tomlString.trim().split(" = '''\n")
  var multilineText = '';
  for (iSection = 0; iSection < multilineSecions.length; iSection++) {
    var multilineSecionTopBottom = multilineSecions[iSection].split("\n'''\n");
    if (multilineSecionTopBottom.length == 1) {
      result = result + multilineSecions[iSection];
    } else {
      for (iTopBottom = 0; iTopBottom < multilineSecionTopBottom.length; iTopBottom++) {
        if (iTopBottom == 0) {
          multilineText = multilineSecionTopBottom[iTopBottom];
          multilineText = multilineText.replace(/"/g, "{{{-dq-}}}")
          multilineText = multilineText.replace(/\[/g, "{{{-lbrack-}}}")
          multilineText = multilineText.replace(/\]/g, "{{{-rbrack-}}}")
          result = result + " = \"\n" + multilineText + "\n\"\n\n";
        } else {
          result = result + multilineSecionTopBottom[iTopBottom];
        }
      }
    }
  }
  return result;
}

function postprocessTOML(tomlString) {
  var result = tomlString;
  result =  result.replace(/{{{-dq-}}}/g, "\\\"");
  result =  result.replace(/{{{-lbrack-}}}/g, "[");
  result =  result.replace(/{{{-rbrack-}}}/g, "]");
  return result;
}
```

https://jsfiddle.net/bixfliz/o2hxgjnd/

**Comment by Jonarod** [comment]
Can you give me samples to test with what the output you expect ?
I am into a solution a bit cleaner and really lightweight :)

**Comment by Jonarod** [comment]
I know I am way after the facts... but check out the new `0.1.1` release with Multi-line string literals support. Hope it can help :)
