### ISSUE TITLE
There is no 'LICENSE' file.

### ISSUE THREAD

**Issue by tasasei** [Jonarod/markty-TOML#9]
I want to use this library in a commercial product.
But there is no 'LICENSE' file so I cannot use.
(I know this library is distributed in the MIT license in npm)

Please make LICENSE file.

And I will be more happy if the distributed file (dist) in unpkg.com would be added a LICENSE sentence.

**Comment by Jonarod** [comment]
Hey there !

Glad this project helps you :)

I have added the LICENSE file.

**Comment by Jonarod** [comment]
@tasasei Would love to know your project by the way if you can share !

**Comment by tasasei** [comment]
@Jonarod 
Thank you for adding the file.
And I'm happy that you are interested in my job.

Unfortunately, I'm not allowed to mention the project.😢

I'm happy to find and use this library !
Thanks !
